"""empty message

Revision ID: 1557ac7a6987
Revises: efbf8a380eea
Create Date: 2020-08-20 16:12:11.983585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1557ac7a6987'
down_revision = 'efbf8a380eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_task')
    op.drop_table('user_to_project')
    op.drop_table('user_to_subject')
    op.drop_table('project_invitation')
    op.drop_table('user_to_project_2')
    op.drop_table('project_rejections')
    op.drop_table('badge_to_perk')
    op.drop_table('user_to_notification')
    op.drop_table('project_to_subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_to_subject',
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_to_subject_ibfk_1'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='project_to_subject_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_to_notification',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notification_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name='user_to_notification_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_to_notification_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('badge_to_perk',
    sa.Column('badge_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('perk_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], name='badge_to_perk_ibfk_1'),
    sa.ForeignKeyConstraint(['perk_id'], ['badge_perk.id'], name='badge_to_perk_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('project_rejections',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_rejections_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='project_rejections_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_to_project_2',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='user_to_project_2_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_to_project_2_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('project_invitation',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_invitation_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='project_invitation_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_to_subject',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='user_to_subject_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_to_subject_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_to_project',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='user_to_project_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_to_project_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_to_task',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='user_to_task_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_to_task_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
