"""empty message

Revision ID: 378f28934863
Revises: 0c1bba9866bd
Create Date: 2020-08-24 14:58:51.429382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378f28934863'
down_revision = '0c1bba9866bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('available', sa.Boolean(), nullable=False))
    op.alter_column('user_subjects', 'user_selected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subjects', 'user_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'available')
    # ### end Alembic commands ###
