"""empty message

Revision ID: 707bb9b6c53c
Revises: e7e5809e35f8
Create Date: 2020-09-30 15:56:10.057155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707bb9b6c53c'
down_revision = 'e7e5809e35f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'pinned')
    # ### end Alembic commands ###
