"""empty message

Revision ID: 782498d2c959
Revises: 988ae76da6b2
Create Date: 2020-08-09 14:37:28.002837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782498d2c959'
down_revision = '988ae76da6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('xp', sa.Integer(), nullable=False))
    op.add_column('user_badge', sa.Column('total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_badge', 'total')
    op.drop_column('user', 'xp')
    # ### end Alembic commands ###
