"""empty message

Revision ID: 98c67a60dbfd
Revises: c68e6416c354
Create Date: 2020-08-23 13:34:27.582823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c67a60dbfd'
down_revision = 'c68e6416c354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subjects', sa.Column('user_selected', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subjects', 'user_selected')
    # ### end Alembic commands ###
