"""empty message

Revision ID: 996e0ec2009e
Revises: 378f28934863
Create Date: 2020-08-24 14:59:15.863670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996e0ec2009e'
down_revision = '378f28934863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('available', sa.Boolean(), nullable=True))
    op.alter_column('user_subjects', 'user_selected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subjects', 'user_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'available')
    # ### end Alembic commands ###
