"""empty message

Revision ID: 9a80c000bd36
Revises: e8ffbd72bbe1
Create Date: 2020-08-10 09:38:52.356837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a80c000bd36'
down_revision = 'e8ffbd72bbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_badge', 'badge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_badge', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_badge', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_badge', 'badge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
