"""empty message

Revision ID: 9c7bae3c0bf2
Revises: e51b63e1a217
Create Date: 2020-08-10 10:25:49.520135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7bae3c0bf2'
down_revision = 'e51b63e1a217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_badge', sa.Column('last_active', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_badge', 'last_active')
    # ### end Alembic commands ###
