"""empty message

Revision ID: aca5d8cf752b
Revises: 9a31c8db18fd
Create Date: 2020-08-20 13:33:47.947647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca5d8cf752b'
down_revision = '9a31c8db18fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'name')
    # ### end Alembic commands ###
