"""empty message

Revision ID: ba26b28a5304
Revises: 47e2ca1ed70c
Create Date: 2020-08-10 10:27:03.792214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba26b28a5304'
down_revision = '47e2ca1ed70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_badge', sa.Column('last_active', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_badge', 'last_active')
    # ### end Alembic commands ###
