"""empty message

Revision ID: bc0b680ff16e
Revises: 996e0ec2009e
Create Date: 2020-08-24 14:59:59.252132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0b680ff16e'
down_revision = '996e0ec2009e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subjects', 'user_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.execute('UPDATE user_subjects SET user_selected = false')
    op.alter_column('user_subjects', 'user_selected', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subjects', 'user_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
