"""empty message

Revision ID: cfc8c12e45e3
Revises: bc0b680ff16e
Create Date: 2020-08-24 15:30:06.911598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc8c12e45e3'
down_revision = 'bc0b680ff16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'available')
    op.execute('UPDATE user SET available = true')
    op.alter_column('user', 'available', nullable=False)
    op.execute('UPDATE user_subjects SET user_selected = false')
    op.alter_column('user_subjects', 'user_selected', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('available', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
