"""empty message

Revision ID: e3b3a1ea419b
Revises: 782498d2c959
Create Date: 2020-08-10 09:33:34.401770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b3a1ea419b'
down_revision = '782498d2c959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_badge', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_badge', 'id')
    # ### end Alembic commands ###
