"""empty message

Revision ID: e51b63e1a217
Revises: 9a80c000bd36
Create Date: 2020-08-10 09:50:03.212671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51b63e1a217'
down_revision = '9a80c000bd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_application', sa.Column('apply_stamp', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_application', 'apply_stamp')
    # ### end Alembic commands ###
