"""empty message

Revision ID: e7e5809e35f8
Revises: 5f6a5cd64476
Create Date: 2020-09-27 16:49:50.069797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e5809e35f8'
down_revision = '5f6a5cd64476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('complete', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
